.TH "apt-listchanges" "1" 
.SH "NAME" 
apt-listchanges \(em Muestra las nuevas entradas 
de los ficheros de cambios de los paquetes de Debian 
 
.SH "SYNOPSIS" 
.PP 
\fBapt-listchanges\fR [\fIopciones\fR \&... ]  {\fB\-\-apt\fP  | \fIpaquete.deb\fR \&... }  
.SH "DESCRIPCIÓN" 
.PP 
\fBapt-listchanges\fR es una herramienta que muestra los 
cambios de una nueva versión de un paquete de Debian respecto a la versión 
instalada actualmente en el sistema. 
.PP 
Esto se realiza extrayendo las entradas relevantes de los ficheros 
NEWS.Debian y changelog[.Debian], normalmente se 
encuentran en 
\fB/usr/doc/\fP\fIpaquete\fR, de los 
archivos de paquetes Debian. 
 
.PP 
Cuando se le proporciona un conjunto de ficheros como argumentos (o leídos 
a través de apt con la opción \fB\-\-apt\fP), 
\fBapt-listchanges\fR analizará los ficheros (asumiendo que 
son archivos de paquetes de Debian) en busca de las entradas relevantes 
del fichero de cambios, y mostrará un resumen, ordenado por urgencia. 
 
.SH "OPCIONES" 
.IP "\fB\-\-apt\fP 	" 10 
Lee los nombres de los ficheros de una tubería con un formato 
especial (tal como lo proporciona apt), en vez de la línea de 
órdenes, y tiene en cuenta ciertas opciones especificas de apt en el 
fichero de configuración. Esta tubería debe estar en el formato de 
la "versión 2", especificado en el fichero de configuración de apt. 
 
.IP "\fB-v, \-\-verbose\fP 	" 10 
Muestra información adicional (normalmente no se quiere). Por 
ejemplo, mostrar un mensaje cuando un paquete con la misma versión o 
anterior va a ser instalado, o cuando es la primera vez que se 
instala el paquete. 
 
.IP "\fB-f, \-\-frontend\fP 	" 10 
Selecciona la interfaz a usar para mostrar la información al 
usuario. Las interfaces actuales son: 
 
.RS 
.IP "pager" 10 
Usa su paginador favorito para mostrar la salida. Por omisión, 
se usará la variable de entorno PAGER. La opción "pager" puede 
especificarse en el fichero de configuración para que 
apt-listchanges use un paginador específico. 
 
.IP "browser" 10 
Muestra los cambios en formato HTML usando un navegador, con 
enlaces para los fallos y las direcciones de correo 
electrónico. Por omisión, se usará la variable de entorno 
BROWSER. La opción "browser" puede especificarse en el fichero 
de configuración para que apt-listchanges use un navegador 
específico. 
 
.IP "xterm-pager" 10 
Usa su paginador favorito para mostrar la salida, pero lo hace 
sobre un xterm (usando la alternativa x-terminal-emulator) de 
fondo. Esto le permite realizar la actualización mientras mira 
los cambios. Puede cambiar el emulador de terminal con la 
opción "xterm". 
 
.IP "xterm-browser" 10 
La combinación lógica de xterm-pager y browser. Apropiada sólo 
para navegadores en modo texto. 
 
.IP "text" 10 
Vuelca la salida a stdout, sin pausas. 
 
.IP "mail" 10 
Manda correos a las direcciones especificadas con 
\-\-email-address, y no muestra los cambios. 
 
.IP "none" 10 
No hace nada. Puede usarse para prevenir que apt-listchanges se 
ejecuta cunado se invoque apt de forma automática. 
 
.RE 
.IP "\fB\-\-email-address=dirección\fP" 10 
Además de mostrar los cambios, mandar una copia a la dirección 
especificada. Si sólo quiere mandar los cambios, use esta opción 
junto con la interfaz 'mail'. 
 
.IP "\fB-c, \-\-confirm\fP" 10 
Una vez que se han mostrado los cambios, preguntar al usuario si 
desea continuar. Si el usuario elige no continuar, se devolverá un 
estado de salida distinto de cero, y apt abortará. 
 
.IP "\fB-a, \-\-all\fP" 10 
En vez de tratar de mostrar los cambios desde la versión instalada, 
simplemente mostrar todos los cambios de todos los paquetes. Esto es 
útil para ver todo el fichero de cambios de un .deb antes de 
extraerlo. 
 
.IP "\fB\-\-save_seen=fichero\fP" 10 
Esta opción hará que apt-listchanges lleve la cuenta de la última 
versión de un paquete para la que se han mostrado los cambios, para 
así, evitar mostrar los mismos cambios en futuras ejecuciones. La 
base de datos se guarda en el fichero especificado. Especifique 
'none' para deshabilitar esta característica. 
 
.IP "\fB\-\-which={news|changelogs|both}\fP" 10 
Esta opción indica si se deben mostrar la noticias (de NEWS.Debian 
et al.), registros de cambios (de changelog.Debian et al.) o 
ambos. Por omisión se muestran ambos. 
 
.IP "\fB\-\-help\fP" 10 
Muestra información acerca de la sintaxis. 
 
.IP "\fB-h, \-\-headers\fP" 10 
Esta opción hará que apt-listchanges inserte una cabecera antes de 
los cambios de cada paquete, mostrando el nombre del paquete, y los 
nombres de los paquetes binarios que van a ser actualizados (si es 
que hay más de uno o difiere respecto del nombre del paquete 
fuente). 
 
.IP "\fB\-\-debug\fP" 10 
Muestra alguna información de depuración. 
.IP "\fB\-\-profile=\fInombre\fR\fP" 10 
Selecciona un perfil. 
\fInombre\fR corresponde a una sección en 
\fB/etc/apt/listchanges.conf\fP.  De forma 
predeterminada, cuando se invoca desde apt es "apt", y "cmdline" en 
otro caso. 
 
.SH "ENTORNO" 
.IP "APT_LISTCHANGES_FRONTEND" 10 
Interfaz a usar 
.IP "BROWSER" 10 
Usado por la interfaz browser, debería ser una orden que 
espere una URL de un fichero en formato HTML a mostrar. 
.SH "FICHEROS" 
.IP "/etc/apt/listchanges.conf" 10 
Fichero de configuración. La mayoría de las opciones tienen el 
nombre de las opciones de la línea de órdenes, con los guiones 
cambiados por guiones bajos. 
.PP 
\fBFichero de configuración de ejemplo\fR 
.PP 
.nf 
[cmdline] 
frontend=pager 
 
[apt] 
frontend=xterm-pager 
email_address=root 
confirm=1 
 
[custom] 
frontend=browser 
browser=mozilla 
 
.fi 
.PP 
.IP "" 10 
El fichero de configuración anterior especifica que, en el modo 
línea de órdenes, la interfaz predeterminada es "pager". 
En modo apt, la interfaz predeterminado es xterm-pager, una copia de 
los cambios (si es que hay algunos) debe enviarse al superusuario, y 
apt-listchanges debe pedir confirmación. Si se invoca a 
apt-listchanges con \-\-profile=custom se usará la interfaz de 
navegador, y se ejecutará mozilla. 
.IP "/var/lib/apt/listchanges.db" 10 
Base de datos usada por save-seen 
.SH "AUTOR" 
.PP 
apt-listchanges fue escrito por Matt Zimmerman 
<mdz@debian.org> 
 
.SH "TRADUCTOR" 
.PP 
Traducción de Rubén Porras Campo 
<debian-l10n-spanish@lists.debian.org> 
 
.SH "VÉASE ADEMÁS" 
.PP 
\fBapt.conf\fP\fB(5)\fP      
.\" created by instant / docbook-to-man, Thu 10 Aug 2006, 20:37 
