.TH "apt-listchanges" "1" 
.SH "NAME" 
apt-listchanges \(em Affiche les nouvelles entrées du 
journal des modifications des paquets de l'archive Debian 
 
.SH "SYNOPSIS" 
.PP 
\fBapt-listchanges\fR [\fIoptions\fR \&... ]  {\fB\-\-apt\fP  | \fIpaquet.deb\fR \&... }  
.SH "DESCRIPTION" 
.PP 
\fBapt-listchanges\fR est un outil qui affiche ce 
qui a changé dans la nouvelle version d'un paquet Debian par rapport 
à la version actuellement installée sur le système. 
 
.PP 
Il réalise cela en extrayant les entrées appropriées des fichiers 
NEWS.Debian et changelog[.Debian], qui se trouvent 
habituellement dans le répertoire 
\fB/usr/share/doc/\fP\fIpaquet\fR, 
de l'archive d'un paquet Debian. 
 
.PP 
Avec des noms de fichiers en argument (ils peuvent être lus depuis apt si 
l'option \fB\-\-apt\fP est utilisée), 
\fBapt-listchanges\fR examine les fichiers (supposés 
être des archives de paquets Debian) à la recherche des entrées appropriées 
et en affiche un résumé trié par ordre d'urgence. 
 
.SH "OPTIONS" 
.IP "\fB\-\-apt\fP         " 10 
Lit les noms de fichiers depuis un tube au format spécial  
(fourni par apt), plutôt que depuis la ligne de commande, 
et respecte certaines options spécifiques à apt dans le fichier de  
configuration. Ce tube doit être au format «\ version\ 2\ »,  
spécifié dans le fichier de configuration d'apt. 
 
.IP "\fB-v, \-\-verbose\fP         " 10 
Affiche des informations additionnelles (généralement non désirées). 
Par exemple, cela affiche un message lorsqu'un paquet d'une version 
identique ou inférieure est sur le point d'être installé, ou lorsqu'un 
paquet est sur le point d'être installé pour la première fois. 
 
.IP "\fB-f, \-\-frontend\fP         " 10 
Sélectionne l'interface à utiliser pour afficher l'information à 
l'utilisateur. Les interfaces disponibles actuellement sont\ : 
 
.RS 
.IP "pager" 10 
Utilise votre pageur favori pour l'affichage. Par défaut, 
la variable d'environnement PAGER sera utilisée. L'option 
«\ pager\ » peut être spécifiée dans le fichier de 
configuration pour sélectionner un pageur spécifique à 
utiliser avec apt-listchanges. 
 
.IP "browser" 10 
Affiche le journal des modifications formaté en HTML dans un 
navigateur web avec des hyperliens vers les pages de bugs et 
pour les adresses électroniques. Par défaut, la variable 
d'environnement PAGER sera utilisée.  L'option 
«\ browser\ » peut être spécifiée dans le fichier de 
configuration pour sélectionner un navigateur spécifique à 
utiliser avec apt-listchanges. 
 
.IP "xterm-pager" 10 
Utilise votre pageur favori pour l'affichage, mais le fait 
dans un xterm  en arrière-plan (en utilisant l'alternative 
pointée par x-terminal-emulator). Cela vous permet de poursuivre 
la mise à jour tout en continuant à consulter le journal des 
modifications. Vous pouvez spécifier l'émulateur de terminal à 
utiliser avec l'option «\ xterm\ » du fichier de configuration. 
 
.IP "xterm-browser" 10 
La conjonction des options xterm-pager et browser. 
Cela convient uniquement aux navigateurs en mode texte. 
 
.IP "text" 10 
Affiche, sans pause, le résultat sur la sortie standard. 
 
.IP "mail" 10 
Envoie un courriel à l'adresse donnée grâce à \-\-email-address sans 
afficher les journaux de modifications. 
 
.IP "none" 10 
Ne fait rien. Cela peut être utilisé pour éviter 
qu'apt-listchanges ne se lance alors qu'il est configuré 
pour se lancer automatiquement depuis apt. 
 
.RE 
.IP "\fB\-\-email-address=adresse\fP" 10 
Affichage du journal des modifications et envoi d'une copie  
à l'adresse spécifiée. Pour ne recevoir les 
journaux de modification que par courriel, utiliser cette 
option avec la pseudo-interface «\ mail\ ». 
 
.IP "\fB-c, \-\-confirm\fP" 10 
Une fois que les journaux de modifications ont été affichés, 
demande à l'utilisateur s'il veut continuer ou interrompre 
l'installation. Si l'utilisateur choisit d'interrompre, une 
valeur de sortie non nulle est renvoyée et apt abandonne. 
 
.IP "\fB-a, \-\-all\fP" 10 
Au lieu d'afficher uniquement les entrées des journaux plus récentes 
que la version du paquet en cours d'installation, affiche 
la totalité du journal des modifications du paquet. C'est 
utile pour voir la totalité du journal contenu dans un paquet .deb 
avant d'extraire ce dernier. 
 
 
.IP "\fB\-\-save_seen=fichier\fP" 10 
Cette option demande à apt-listchanges de garder 
une trace de la dernière version d'un paquet pour 
laquelle le journal à été affichée afin d'éviter 
de réafficher le même journal la fois suivante. La base 
de données est conservée dans le fichier donné en argument. 
Spécifiez «\ none\ » pour désactiver cette fonctionnalité. 
 
.IP "\fB\-\-which={news|changelogs|both}\fP" 10 
Cette option permet de choisir entre l'affichage des messages 
de nouveautés (récupérés dans NEWS.Debian et d'autres), des journaux de 
modifications (récupérés dans changelog.Debian et d'autres) ou des deux. 
Par défaut, les deux sont affichés. 
 
.IP "\fB\-\-help\fP" 10 
Affiche une aide courte. 
 
.IP "\fB-h, \-\-headers\fP" 10 
Ces options permettent de faire insérer, par apt-listchanges, un 
en-tête avant le journal de chaque paquet indiquant son nom, 
et le nom des paquets binaires qui sont en train d'être mis 
à jour (s'il y en a plus d'un ou s'il diffère du nom du paquet 
source). 
 
.IP "\fB\-\-debug\fP" 10 
Affiche des informations de débogage. 
 
.IP "\fB\-\-profile=\fInom\fR\fP" 10 
Sélectionne un profil d'options. 
\fInom\fR correspond à une section dans le fichier 
\fB/etc/apt/listchanges.conf\fP.  Les valeurs par défaut 
sont «\ apt\ » lors d'un appel depuis apt et «\ cmdline\ » sinon. 
 
.SH "ENVIRONNEMENT" 
.IP "APT_LISTCHANGES_FRONTEND" 10 
Interface à utiliser. 
.IP "BROWSER" 10 
Utilisée par l'interface browser, elle devrait contenir une commande 
qui attend l'URL d'un fichier HTML à afficher). 
.SH "FICHIER" 
.IP "/etc/apt/listchanges.conf" 10 
Fichier de configuration. La plupart des options ont le même nom 
que l'option équivalente en ligne de commande à l'exception d'éventuels 
traits d'union qui doivent être remplacés par des traits de soulignement. 
 
.PP 
\fBExemple de fichier de configuration\fR 
.PP 
.nf 
[cmdline] 
frontend=pager 
 
[apt] 
frontend=xterm-pager 
email_address=root 
confirm=1 
 
[perso] 
frontend=browser 
browser=mozilla 
.fi 
.PP 
.IP "" 10 
Le fichier de configuration précédent indique que 
dans le mode ligne de commande, l'interface par défaut 
doit être «\ pager\ ». Dans le mode apt, 
l'interface sera par défaut xterm-pager, une copie des 
journaux (s'il y en a) devra être envoyée au super utilisateur 
(«\ root\ ») et apt-listchanges demandera une confirmation. 
Si apt-listchanges est appelé avec \-\-profile=perso, l'interface browser 
sera utilisée et lancera mozilla. 
.IP "/var/lib/apt/listchanges.db" 10 
Base de données des déja-vus 
.SH "AUTEUR" 
.PP 
apt-listchanges a été écrit par Matt Zimmerman 
<mdz@debian.org> 
 
.SH "VOIR AUSSI" 
.PP 
\fBapt.conf\fP\fB(5)\fP      
.SH "TRADUCTEUR" 
.PP 
Traduction d'Olivier Trichet <olivier.trichet@centrale-lille.net>, août 2004 
 
.\" created by instant / docbook-to-man, Thu 10 Aug 2006, 20:37 
