#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

# Ask our questions
db_input medium apt-listchanges/apt-hook-p || true
db_input medium apt-listchanges/apt-mode-frontend || true
db_go

db_get apt-listchanges/apt-mode-frontend
if [ "$RET" = "mail" ]; then
  db_input medium apt-listchanges/apt-mode-email-address || true
  db_go
fi
