#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

# Ask our questions
db_input medium apt-listchanges/overwrite_etc_apt_listchanges_conf || true
db_go

db_get apt-listchanges/overwrite_etc_apt_listchanges_conf
if [ "$RET" = "true" ]; then
    db_input medium apt-listchanges/frontend || true
    db_input medium apt-listchanges/save-seen || true
    db_input medium apt-listchanges/email-address || true
    db_input medium apt-listchanges/confirm || true
    db_go
fi

# Clean up questions we used to ask (1.14 and earlier)
db_unregister apt-listchanges/apt-mode-frontend || true
db_unregister apt-listchanges/apt-mode-email-address || true
db_unregister apt-listchanges/apt-mode-display-mode || true
# 2.3 and earlier
db_unregister apt-listchanges/apt-hook-p || true

exit 0
