#!/bin/sh

set -e

hook=/etc/apt/apt.conf.d/20listchanges

if test -d /usr/lib/site-python; then
    rm -f /usr/lib/site-python/apt_listchanges.pyo
    rm -f /usr/lib/site-python/apt_listchanges.pyc
    rm -f /usr/lib/site-python/DebianControlParser.pyo
    rm -f /usr/lib/site-python/DebianControlParser.pyo
fi

if [ -f $hook.disabled ]; then
    mv $hook.disabled $hook
fi

#DEBHELPER#

exit 0
